### ISSUE TITLE
Embed link to artist info for each search result

### ISSUE THREAD

**Issue by chynu** [chynu/cs4300sp2021-ag2496-cc972-mb2359-jjz67-jxl8#2]
- [x] Front-end: include artist info in template
- [x] Back-end: get artist link from database
- [x] Data: Add artist link into csv

 
Types of data we can use for "link":
 - YouTube channel link
 - Spotify link
 - Spotify code (allows for embedding a Spotify player directly in the result..?)
     - [Link on how to embed](https://developer.spotify.com/documentation/widgets/generate/embed/)

**Comment by jerilynzheng** [comment]
Got Spotify artist link and put it into the csv
